#!/bin/bash

scripts_dir="~/scripts"
current_bash=".bashrc_default"

# Check scripts dir
[ ! -d $scripts_dir ] && mkdir -p $scripts_dir

# copy .sh files to scripts dir
cp bash_scripts/*.sh ${scripts_dir}

# cp .bashrc to home dir
cat ${current_bash} >> ~/.bashrc
