#!/bin/bash

# scripts_dir=~/scripts/
# current_bash=".bashrc_new"

scripts_dir=$1
current_bash=$2

# copy .sh files to scripts dir
cp bash_scripts/*.sh ${scripts_dir}

# cp .bashrc to home dir
cp ${current_bash} ~/.bashrc
